### ISSUE TITLE
Status 405

### ISSUE THREAD

**Issue by Klaudioz** [kevinjalbert/notion-heroku#6]
Hello, I've been following your tutorials and I've getting a 504 error on Heroku:

![image](https://user-images.githubusercontent.com/632625/70476474-f9b31800-1a93-11ea-8fa1-61047ddd263c.png)

![image](https://user-images.githubusercontent.com/632625/70476265-95905400-1a93-11ea-9e1e-0d26401da435.png)

![image](https://user-images.githubusercontent.com/632625/70476275-9c1ecb80-1a93-11ea-85e2-4f1fed3922ba.png)

I got the same using http or google assistant.

Thanks for you great job with this.

**Comment by kevinjalbert** [comment]
@Klaudioz Ah yep this is likely because I've changed the API since I started. So the blog post and README are _slightly_ out of date (I've been meaning to get around to updated them -- but I just haven't made it a priority).

https://github.com/kevinjalbert/notion-heroku/commit/471d6c12365eaee7b0eadadd621b86580d38c6b7#diff-da3fed2ed312ed177133617b30862a7d

In the above commit, I changed the API endpoints for `add_note` and `add_task` to be POST instead of GET. So you'll have to make POST requests instead.

At the same time there is now authentication present that must be used with the requests (either via the HEADER or `api_token` attribute in the request body), for added security.

I recommend using `curl` or something like [Postman](https://www.getpostman.com/downloads/) to make those POST requests as you cannot do it via the browser's URL bar anymore.

-----

I've closed the issue, but continue in the thread if there is additional questions related to this.

**Comment by Klaudioz** [comment]
Thanks for your answer. Using POST I got always error 500:

2019-12-10T03:51:46.314581+00:00 heroku[router]: at=info method=POST path="/add_note?title=%20this%20is%20working%20finally" host=notionga.herokuapp.com request_id=8256db3c-962b-4b9d-ac43-d3baf11cf8e5 fwd="34.239.101.36" dyno=web.1 connect=0ms service=43ms status=500 bytes=200 protocol=https

Why I did with IFTTT:

![image](https://user-images.githubusercontent.com/632625/70493744-f46ec100-1ac5-11ea-9d0e-cf53ea38b99c.png)

**Comment by kevinjalbert** [comment]
For reference the way mine looks is like: 
![](https://api.monosnap.com/file/download?id=AHnCPgucWLjsThUapbaEj8pCfTdExz)
