### ISSUE TITLE
Web Request sends query string but code looks for body

### ISSUE THREAD

**Issue by Vinecnt** [kevinjalbert/notion-heroku#8]
In step 6, we attach the textField to the query string in the URL but the code is looking for the textField/title in the response body as show in line 74.
![image](https://user-images.githubusercontent.com/14827962/70575191-f2633b80-1b73-11ea-8d86-12186f2efad7.png)
The fix would simply put 
`{ "title":"{{TextField}}" }`
in the web request body or put the appropriate key-value depending on the webhook

**Comment by kevinjalbert** [comment]
Hey @Vinecnt, this is an artifact of me not getting around to updating the steps and images. I've since made changes so that these endpoints accept data via POST, and thus via the request body.

This is expected behaviour at this point, and the issue is in the README. I'll see to updating it within the next few days as this is the second time this came up via an issue.
